# Generated by Django 3.2 on 2024-11-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='sensor4_value',
            field=models.IntegerField(default=0),
        ),
    ]
