# Generated by Django 3.2 on 2024-11-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_app', '0003_remove_sensordata_sensor4_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='sensor1_value',
            new_name='potentiometer',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='sensor2_value',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='sensor3_value',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
    ]
